import sqlite3
from pathlib import Path
from rapidfuzz import fuzz

_STOPWORDS = {"the", "a", "an", "to", "for", "and", "or", "in", "of", "with", "on", "is", "it", "fix", "debug"}


def _keywords(text: str) -> set[str]:
    return {w.lower() for w in text.split() if w.lower() not in _STOPWORDS and len(w) > 2}


def cluster_runs(conn: sqlite3.Connection, min_runs: int = 3) -> list[dict]:
    runs = conn.execute("SELECT id, user_goal, outcome FROM runs").fetchall()
    assigned: set[str] = set()
    clusters = []

    for i, r1 in enumerate(runs):
        if r1["id"] in assigned:
            continue
        cluster = [r1]
        kw1 = _keywords(r1["user_goal"])

        for j, r2 in enumerate(runs):
            if i == j or r2["id"] in assigned:
                continue
            kw2 = _keywords(r2["user_goal"])
            if kw1 and kw2:
                overlap = len(kw1 & kw2) / max(len(kw1), len(kw2))
            else:
                overlap = 0.0
            fuzzy = fuzz.partial_ratio(r1["user_goal"], r2["user_goal"])
            if overlap >= 0.3 or fuzzy >= 70:
                cluster.append(r2)

        if len(cluster) < min_runs:
            continue

        for r in cluster:
            assigned.add(r["id"])

        run_ids = [r["id"] for r in cluster]
        ph = ",".join("?" * len(run_ids))
        top_tools = conn.execute(
            f"SELECT tool_name, COUNT(*) as cnt FROM tool_calls WHERE run_id IN ({ph}) GROUP BY tool_name ORDER BY cnt DESC LIMIT 5",
            run_ids,
        ).fetchall()
        error_count = conn.execute(
            f"SELECT COUNT(*) FROM errors WHERE run_id IN ({ph})", run_ids
        ).fetchone()[0]

        kws = sorted(_keywords(cluster[0]["user_goal"]))[:3]
        category = "-".join(kws) if kws else "general"
        has_success = any(r["outcome"] == "shipped" for r in cluster)

        clusters.append({
            "category": category,
            "run_count": len(cluster),
            "run_ids": run_ids,
            "has_success": has_success,
            "top_tools": [(r["tool_name"], r["cnt"]) for r in top_tools],
            "error_count": error_count,
            "sample_goal": cluster[0]["user_goal"],
        })

    return clusters


def generate_skill_md(category: str, cluster: dict, conn: sqlite3.Connection) -> str:
    tools_str = ", ".join(f"{n} ({c}×)" for n, c in cluster["top_tools"])
    shipped = [
        rid for rid in cluster["run_ids"]
        if conn.execute("SELECT outcome FROM runs WHERE id=?", (rid,)).fetchone()["outcome"] == "shipped"
    ]
    pattern_lines = []
    if shipped:
        cmds = conn.execute(
            "SELECT command FROM shell_commands WHERE run_id=? ORDER BY timestamp LIMIT 10",
            (shipped[0],),
        ).fetchall()
        pattern_lines = [f"  {i + 1}. `{r['command']}`" for i, r in enumerate(cmds)]
    pattern = "\n".join(pattern_lines) if pattern_lines else "  (no shell commands recorded)"
    return f"""# {category}

## Problem
{cluster['sample_goal']}

## Evidence
- Seen in {cluster['run_count']} sessions
- Top tools: {tools_str}
- Errors across sessions: {cluster['error_count']}

## Successful Pattern
{pattern}

## Notes
Generated by `afr extract-skills`. Review before using as an agent skill.
"""


def run_extraction(conn: sqlite3.Connection, min_runs: int = 3) -> None:
    from rich.console import Console
    from rich.prompt import Confirm

    console = Console()
    clusters = [c for c in cluster_runs(conn, min_runs) if c["has_success"]]

    if not clusters:
        console.print(f"[yellow]No clusters with {min_runs}+ runs and a shipped outcome found.[/yellow]")
        console.print("[dim]Tip: tag sessions with `afr tag <id> shipped` first.[/dim]")
        return

    for cluster in clusters:
        console.print(f"\n[bold cyan]Candidate:[/bold cyan] {cluster['category']}")
        console.print(f"  {cluster['run_count']} sessions | tools: {', '.join(t for t, _ in cluster['top_tools'])} | errors: {cluster['error_count']}")
        if Confirm.ask("  Generate SKILL.md?"):
            content = generate_skill_md(cluster["category"], cluster, conn)
            out = Path("generated_skills") / cluster["category"]
            out.mkdir(parents=True, exist_ok=True)
            (out / "SKILL.md").write_text(content, encoding="utf-8")
            console.print(f"  [green]Written â†’ {out / 'SKILL.md'}[/green]")
